# Generated by Django 2.2.4 on 2021-01-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
